# Generated by Django 3.2.3 on 2021-11-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='image',
        ),
    ]
