# Generated by Django 3.2.3 on 2021-11-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_remove_basket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
